import"./assets/styles-DAQgCTTH.js";import{a as g,S as B,i as a}from"./assets/vendor-BwJ01-pp.js";g.defaults.baseURL="https://pixabay.com/api/";async function L(e,o=1){try{return(await g.get("",{params:{per_page:15,page:o,key:"50295834-c918df4fa87d72bde5e1e5104",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(t){throw console.error("API Error:",t),t}}const b=document.querySelector(".gallery"),l=document.querySelector(".loader"),c=document.querySelector(".loadMoreBtn"),R=new B(".gallery a",{captionsData:"alt",captionDelay:250});function S(e){const o=e.map(t=>{const M=["likes","views","comments","downloads"].map(f=>`<p class="info-item">${q(f)}:<span class="info">${t[f]}</span></p>`).join("");return`<li class="image-item">
    <a href="${t.largeImageURL}" title="${t.tags}">
    <img src="${t.webformatURL}" 
    alt="${t.tags}"
    />
    </a>
    <div class="gallery-info">
    ${M}
    </div>
    </li>`}).join("");b.insertAdjacentHTML("beforeend",o),R.refresh()}function q(e){return e&&e.charAt(0).toUpperCase()+e.slice(1).toLowerCase()}function m(){b.innerHTML=""}function w(){l&&(l.style.display="inline-block")}function p(){l&&(l.style.display="none")}function k(){c&&(c.style.display="inline-block")}function r(){c&&(c.style.display="none")}const D=document.querySelector(".form"),y=document.querySelector('input[name="search-text"]'),h=document.querySelector('button[type="submit"]'),$=document.querySelector(".gallery"),C=document.querySelector(".loadMoreBtn"),E=15;let n=0,s=1,i="";document.addEventListener("DOMContentLoaded",()=>{u(),r(),p()});y.addEventListener("input",u);D.addEventListener("submit",async e=>{e.preventDefault();const o=y.value.trim();if(o!==i&&(s=1,n=0,m(),r()),i=o,!u()){a.error({title:"Поле не може бути порожнім",message:"Будь ласка, введіть текст для пошуку.",position:"topRight"}),r();return}w();try{const t=await L(i,s),d=t.hits;n=t.totalHits,d.length===0?(a.info({title:"Відхилено",message:"За Вашим запитом зображень не знайдено.",position:"topRight"}),r()):(S(d),v())}catch{a.error({title:"Помилка",message:"Під час завантаження зображень сталася помилка. Спробуйте ще раз.",position:"topRight"}),m(),r()}finally{p(),u()}});function u(){return y.value.trim()!==""?(h.disabled=!1,!0):(h.disabled=!0,!1)}C.addEventListener("click",async()=>{s++,w(),r();try{const o=(await L(i,s)).hits;S(o),v(),T()}catch{a.error({title:"Помилка",message:"Під час завантаження додаткових зображень сталася помилка. Спробуйте ще раз.",position:"topRight"}),r()}finally{p()}});function v(){const e=Math.ceil(n/E);s>=e||n===0?(r(),n>0&&a.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})):k()}function T(){const e=$.firstElementChild;if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
